# Conexión a la nube de Aiven
spring.datasource.url=jdbc:mysql://fitup-db-fitup-project.e.aivencloud.com:19725/defaultdb?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (Para que Java entienda a MySQL)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true